apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: candidates
  name: candidates
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: candidates
    spec:
      containers:
        - image: anishainas/candidates:latest
          name: candidates
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
