version: '3'
services:
  candidates:
    build:
      context: candidates
      dockerfile: Dockerfile
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./candidates:/code
    depends_on:
      - redis
    networks:
      - lognet
  vote:
    build:
      context: vote
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./vote:/code
    depends_on:
      - redis
      - candidates
    networks:
      - lognet
  leaderboard:
    build:
      context: leaderboard
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./leaderboard:/code
    depends_on:
      - redis
      - candidates
    networks:
      - lognet
  reset:
    build:
      context: reset
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./reset:/code
    depends_on:
      - redis
    networks:
      - lognet
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lognet
networks:
  lognet:
    driver: bridge