version: '3'
services:
  candidates:
    build:
      context: candidates
      dockerfile: Dockerfile
    image: anishainas/candidates:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - lognet
  vote:
    build:
      context: vote
      dockerfile: Dockerfile
    image: anishainas/vote:latest
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - candidates
    networks:
      - lognet
  leaderboard:
    build:
      context: leaderboard
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - redis
      - candidates
    networks:
      - lognet
  reset:
    build:
      context: reset
      dockerfile: Dockerfile
    image: anishainas/reset:latest
    ports:
      - "5003:5003"
    depends_on:
      - redis
    networks:
      - lognet
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lognet
networks:
  lognet:
    driver: bridge