version: '3'
services:
  candidates:
    build:
      context: candidates
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./candidates:/code
    links:
      - redis
  vote:
    build:
      context: vote
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./vote:/code
    links:
      - redis
  leaderboard:
    build:
      context: leaderboard
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./leaderboard:/code
    links:
      - redis
  reset:
    build:
      context: reset
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./reset:/code
    links:
      - redis
  redis:
    image: redis
